/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  UiColor,
  UiSize,
} from './utils/ui-types';

export namespace Components {
  interface UiApp {
    /**
    * Background color from the UI Color Palette
    */
    'background': UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color': UiColor;
    /**
    * Absolute font size
    */
    'size': UiSize;
  }
  interface UiAppBody {
    /**
    * Background color from the UI Color Palette
    */
    'background': UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color': UiColor;
    /**
    * Absolute font size
    */
    'size': UiSize;
  }
  interface UiAppHeader {
    /**
    * Background color from the UI Color Palette
    */
    'background': UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color': UiColor;
    /**
    * Absolute font size
    */
    'size': UiSize;
    'src': string;
  }
  interface UiAppNavigation {
    /**
    * Background color from the UI Color Palette
    */
    'background': UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color': UiColor;
    /**
    * Absolute font size
    */
    'size': UiSize;
    'toggle': () => Promise<void>;
  }
  interface UiButton {
    /**
    * Background color from the UI Color Palette
    */
    'background': UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color': UiColor;
    /**
    * Absolute font size
    */
    'size': UiSize;
    'type': string;
  }
  interface UiIcon {}
  interface UiRipple {
    'toggle': (e: CustomEvent<any>) => Promise<void>;
  }
}

declare global {


  interface HTMLUiAppElement extends Components.UiApp, HTMLStencilElement {}
  var HTMLUiAppElement: {
    prototype: HTMLUiAppElement;
    new (): HTMLUiAppElement;
  };

  interface HTMLUiAppBodyElement extends Components.UiAppBody, HTMLStencilElement {}
  var HTMLUiAppBodyElement: {
    prototype: HTMLUiAppBodyElement;
    new (): HTMLUiAppBodyElement;
  };

  interface HTMLUiAppHeaderElement extends Components.UiAppHeader, HTMLStencilElement {}
  var HTMLUiAppHeaderElement: {
    prototype: HTMLUiAppHeaderElement;
    new (): HTMLUiAppHeaderElement;
  };

  interface HTMLUiAppNavigationElement extends Components.UiAppNavigation, HTMLStencilElement {}
  var HTMLUiAppNavigationElement: {
    prototype: HTMLUiAppNavigationElement;
    new (): HTMLUiAppNavigationElement;
  };

  interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {}
  var HTMLUiButtonElement: {
    prototype: HTMLUiButtonElement;
    new (): HTMLUiButtonElement;
  };

  interface HTMLUiIconElement extends Components.UiIcon, HTMLStencilElement {}
  var HTMLUiIconElement: {
    prototype: HTMLUiIconElement;
    new (): HTMLUiIconElement;
  };

  interface HTMLUiRippleElement extends Components.UiRipple, HTMLStencilElement {}
  var HTMLUiRippleElement: {
    prototype: HTMLUiRippleElement;
    new (): HTMLUiRippleElement;
  };
  interface HTMLElementTagNameMap {
    'ui-app': HTMLUiAppElement;
    'ui-app-body': HTMLUiAppBodyElement;
    'ui-app-header': HTMLUiAppHeaderElement;
    'ui-app-navigation': HTMLUiAppNavigationElement;
    'ui-button': HTMLUiButtonElement;
    'ui-icon': HTMLUiIconElement;
    'ui-ripple': HTMLUiRippleElement;
  }
}

declare namespace LocalJSX {
  interface UiApp {
    /**
    * Background color from the UI Color Palette
    */
    'background'?: UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color'?: UiColor;
    /**
    * Absolute font size
    */
    'size'?: UiSize;
  }
  interface UiAppBody {
    /**
    * Background color from the UI Color Palette
    */
    'background'?: UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color'?: UiColor;
    /**
    * Absolute font size
    */
    'size'?: UiSize;
  }
  interface UiAppHeader {
    /**
    * Background color from the UI Color Palette
    */
    'background'?: UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color'?: UiColor;
    /**
    * Absolute font size
    */
    'size'?: UiSize;
    'src'?: string;
  }
  interface UiAppNavigation {
    /**
    * Background color from the UI Color Palette
    */
    'background'?: UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color'?: UiColor;
    /**
    * Absolute font size
    */
    'size'?: UiSize;
  }
  interface UiButton {
    /**
    * Background color from the UI Color Palette
    */
    'background'?: UiColor;
    /**
    * Forground color from the UI Color Palette
    */
    'color'?: UiColor;
    'onUiClick'?: (event: CustomEvent<any>) => void;
    /**
    * Absolute font size
    */
    'size'?: UiSize;
    'type'?: string;
  }
  interface UiIcon {}
  interface UiRipple {}

  interface IntrinsicElements {
    'ui-app': UiApp;
    'ui-app-body': UiAppBody;
    'ui-app-header': UiAppHeader;
    'ui-app-navigation': UiAppNavigation;
    'ui-button': UiButton;
    'ui-icon': UiIcon;
    'ui-ripple': UiRipple;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ui-app': LocalJSX.UiApp & JSXBase.HTMLAttributes<HTMLUiAppElement>;
      'ui-app-body': LocalJSX.UiAppBody & JSXBase.HTMLAttributes<HTMLUiAppBodyElement>;
      'ui-app-header': LocalJSX.UiAppHeader & JSXBase.HTMLAttributes<HTMLUiAppHeaderElement>;
      'ui-app-navigation': LocalJSX.UiAppNavigation & JSXBase.HTMLAttributes<HTMLUiAppNavigationElement>;
      'ui-button': LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
      'ui-icon': LocalJSX.UiIcon & JSXBase.HTMLAttributes<HTMLUiIconElement>;
      'ui-ripple': LocalJSX.UiRipple & JSXBase.HTMLAttributes<HTMLUiRippleElement>;
    }
  }
}


